#!/bin/bash
set -euo pipefail


echo "Restic repository: '${RESTIC_REPOSITORY}'"
if restic cat config > /dev/null; then
    echo "Restic repository found"
else
    echo "Initializing new restic repository ..."
    if restic init; then
      echo "Repository successfully initialized."
    else
      echo "Failed to init restic repository!"
      exit 1
    fi
fi

set +e
restic $@
rc=$?
set -e

if [ $rc -ne 0 ]; then
    eval ${POST_COMMAND_FAILURE:-}
    exit $rc
else
    eval ${POST_COMMAND_SUCCESS:-}
fi
